services:
  - type: worker
    name: telegram-tenis-bot
    runtime: python
    plan: starter
    buildCommand: |
      pip install -r requirements.txt
      playwright install
    startCommand: python main.py
    autoDeploy: true