services:
  - type: worker
    name: winamax-bot
    runtime: python
    region: frankfurt
    plan: starter
    buildCommand: |
      pip install -r requirements.txt
      playwright install
    startCommand: python main.py